server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Password123
    url: jdbc:mysql://localhost:31090/jstoredb?characterEncoding=utf8&useSSL=true&useUnicode=true
    username: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update
    show-sql: true
  http:
    encoding:
      charset:utf-8
      force:true
      enabled:true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: jstore