server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true

#security:
#  enable-csrf: false

spring:
#  security:
#    csrf:
#      enabled: false  # 开启CSRF保护
#    user:
#      name: user
#      password: 123456
  mvc:
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://192.168.0.107:3306/jstoremini?characterEncoding=utf8&useSSL=true&useUnicode=true
    username: rayuser
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update
    show-sql: true
  http:
    encoding:
      charset:utf-8
      force:true
      enabled:true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: jstore