## based on
##
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config-jstore-pod
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
      - "/home/jstore/log/*.log"
    
    output.elasticsearch:
      hosts: ['elasticsearch:9200']