## based on
##
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config-jstore-pod
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      enabled: true
      exclude_lines: ['^$']
      multiline:
        pattern: '^\d{4}-\d{1,2}-\d{1,2}\s\d{1,2}:\d{1,2}:\d{1,2}'
        negate: true
        match: after
      paths:
      - "/home/jstore/log/*.log"
      fields:
        log_source: fileschedule_info
    
    output.elasticsearch:
      hosts: ['elasticsearch:9200']