## based on
## https://www.cnblogs.com/gered/p/15386300.html
## https://blog.csdn.net/qq_36266502/article/details/107442196 use es pipeline
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config-jstore-pod
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
      - "/home/jstore/log/*.log"
    
    output.elasticsearch:
      hosts: ['elasticsearch:9200']
      index: "jstore-log-*"