apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-testapi
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.foobar.com
      secretName: tls-secret
  rules:
    - host: www.foobar.com
      http:
        paths:
          - path: /jigsaw(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: jigsaw
                port:
                  number: 80
          - path: /testapi(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: testapi
                port:
                  number: 9009
          - path: /kibana(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: kibana
                port:
                  number: 5601
